import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { cn } from "@/lib/utils";
import ContextProvider from "./contexProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(`${inter.className}`, 'bg-slate-100')}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
